apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-service
  labels:
    app: validation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-service
  template:
    metadata:
      labels:
        app: validation-service
    spec:
      serviceAccountName: examflow-ksa
      containers:
        - name: validation-service
          image: europe-west1-docker.pkg.dev/bitirme-pubsub/examflow-images/examflow-validation:latest
          ports:
            - containerPort: 8080
          env:
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: GCP_PROJECT_ID
            - name: PUBSUB_VALIDATION_SUBSCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: PUBSUB_VALIDATION_SUBSCRIPTION
            - name: PUBSUB_VALIDATED_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: PUBSUB_VALIDATED_TOPIC
            - name: PORT
              value: "8080"
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: MONGODB_PORT
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: MONGODB_DATABASE
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: examflow-secret
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: examflow-secret
                  key: MONGODB_PASSWORD
            - name: MONGODB_URI
              value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@$(MONGODB_HOST):$(MONGODB_PORT)/$(MONGODB_DATABASE)?authSource=admin"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10