apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-service
  labels:
    app: validation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-service
  template:
    metadata:
      labels:
        app: validation-service
    spec:
      containers:
        - name: validation-service
          image: europe-west1-docker.pkg.dev/bitirme-pubsub/examflow-images/examflow-validation:latest
          ports:
            - containerPort: 8080
          env:
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: GCP_PROJECT_ID
            - name: PUBSUB_VALIDATION_SUBSCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: PUBSUB_VALIDATION_SUBSCRIPTION
            - name: PORT
              value: "8080"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
