apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-service
  labels:
    app: exam-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-service
  template:
    metadata:
      labels:
        app: exam-service
    spec:
      serviceAccountName: examflow-ksa
      containers:
        - name: exam-service
          image: europe-west1-docker.pkg.dev/bitirme-pubsub/examflow-images/examflow-exam:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: GCP_PROJECT_ID
            - name: PUBSUB_EXAM_SUBSCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: PUBSUB_EXAM_SUBSCRIPTION
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
