apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: examflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      serviceAccountName: examflow-ksa
      containers:
        - name: api-service
          image: europe-west1-docker.pkg.dev/bitirme-pubsub/examflow-images/examflow-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: GCP_PROJECT_ID
            - name: PUBSUB_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: PUBSUB_TOPIC
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: examflow-config
                  key: PORT
            - name: APP_ENV
              valueFrom:
                secretKeyRef:
                  name: examflow-secret
                  key: APP_ENV
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3