apiVersion: v1
kind: Secret
metadata:
  name: examflow-secret
  namespace: examflow
type: Opaque
stringData:
  APP_ENV: "staging"
  JWT_SECRET: "examflow-dev-jwt-secret-change-me"
  MONGODB_USERNAME: "examflow"
  MONGODB_PASSWORD: "examflow-dev-password"
