apiVersion: v1
kind: ConfigMap
metadata:
  name: examflow-config
  namespace: examflow
data:
  GCP_PROJECT_ID: "bitirme-pubsub"
  PUBSUB_TOPIC: "document-events"
  PUBSUB_SUBSCRIPTION: "document-events-worker"
  PUBSUB_PROCESSED_TOPIC: "document-events"
  PUBSUB_EXAM_SUBSCRIPTION: "document-events-exam"
  PUBSUB_VALIDATION_SUBSCRIPTION: "document-events-validation"
  PUBSUB_VALIDATED_TOPIC: "document-events"
  MONGODB_HOST: "mongodb"
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: "examflow"
  PORT: "8080"
