resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - app-secret.yaml

  - api-deployment.yaml
  - api-service.yaml
  - api-hpa.yaml
  - api-pdb.yaml

  - exam-service/deployment.yaml
  - exam-service/service.yaml

  - validation-service/deployment.yaml
  - validation-service/service.yaml

  - worker-deployment.yaml
