apiVersion: v1
kind: ServiceAccount
metadata:
  name: examflow-ksa
  namespace: examflow
  annotations:
    iam.gke.io/gcp-service-account: examflow-sa@project-ae272ac8-a64f-4afa-8b7.iam.gserviceaccount.com
